title: Project
frontmatter: project
cases:
  - title: invalid type errors
    raw: frontmatter
    normalized: {}
    errors: 1
  - title: empty object returns self
    raw: {}
    normalized: {}
  - title: full object returns self
    raw:
      id: my/project
      title: frontmatter
      description: project frontmatter
      venue:
        title: test
      authors:
        - id: jd
          name: John Doe
          nameParsed:
            literal: John Doe
            given: John
            family: Doe
          affiliations:
            - univa
      affiliations:
        - id: univa
          name: University A
      date: '14 Dec 2021'
      doi: 10.1000/abcd/efg012
      arxiv: https://arxiv.org/example
      open_access: true
      license: {}
      github: https://github.com/example
      binder: https://example.com/binder
      source: https://example.com/source
      subject: ''
      biblio: {}
      oxa: ''
      math:
        a: b
      keywords:
        - example
        - test
      exports:
        - format: pdf
          template: default
          output: out.tex
          a: 1
          article: my-file.md
        - format: xml
          article: my-file.md
          sub_articles:
            - my-notebook.ipynb
      requirements:
        - requirements.txt
      resources:
        - my-script.sh
      copyright: Authors et al.
    normalized:
      id: my/project
      title: frontmatter
      description: project frontmatter
      venue:
        title: test
      authors:
        - id: jd
          name: John Doe
          nameParsed:
            literal: John Doe
            given: John
            family: Doe
          affiliations:
            - univa
      affiliations:
        - id: univa
          name: University A
      date: '2021-12-14'
      doi: 10.1000/abcd/efg012
      arxiv: https://arxiv.org/example
      open_access: true
      license: {}
      github: https://github.com/example
      binder: https://example.com/binder
      source: https://example.com/source
      subject: ''
      biblio: {}
      oxa: ''
      math:
        a:
          macro: b
      keywords:
        - example
        - test
      exports:
        - format: pdf
          template: default
          output: out.tex
          a: 1
          articles:
            - file: my-file.md
        - format: xml
          articles:
            - file: my-file.md
          sub_articles:
            - my-notebook.ipynb
      requirements:
        - requirements.txt
      resources:
        - my-script.sh
      copyright: Authors et al.
  - title: boolean numbering is valid
    raw:
      numbering: 'false'
    normalized:
      numbering:
        all:
          enabled: false
  - title: invalid doi errors
    raw:
      doi: ''
    normalized: {}
    errors: 1
  - title: github username/repo coerces
    raw:
      github: example/repo
    normalized:
      github: https://github.com/example/repo
  - title: invalid github errors
    raw:
      github: https://example.com
    normalized: {}
    errors: 1
  - title: invalid arxiv errors
    raw:
      arxiv: https://example.com
    normalized: {}
    errors: 1
  - title: invalid math errors
    raw:
      math:
        a: valid
        b: 0
    normalized:
      math:
        a:
          macro: valid
    errors: 1
  - title: bibliography string coerces
    raw:
      bibliography: article.bib
    normalized:
      bibliography:
        - article.bib
  - title: settings output_stderr
    raw:
      settings:
        output_stderr: remove
        stdout_output: warn
    errors: 0
    normalized:
      settings:
        output_stderr: remove
        output_stdout: warn
  - title: settings output_stderr bad value
    raw:
      settings:
        output_stderr: ok
        output_stdout: ok
    errors: 2
    normalized: {}
  - title: settings unknown value
    raw:
      settings:
        what: ok
    warnings: 1
    normalized: {}
  - title: invalid copyright errors
    raw:
      copyright: {}
    normalized: {}
    errors: 1
  - title: parts are validated
    raw:
      abstract: |-
        Just an example part!
      data_availability: Example
      parts:
        example_part: |-
          Another example part!
    normalized:
      parts:
        abstract:
          - Just an example part!
        data_availability:
          - Example
        example_part:
          - Another example part!
